stages:
  - build
  - test

Buildimg:
  stage: build
  tags:
    - sloganindo
  script:
#    - docker build -t slogan .
#    - docker ps
    - echo OkOk

Test:
  stage: test
  tags:
    - sloganindo
  script:
    - docker run --rm -e nicname="joe" slogan | grep "hi"
    
       