variables:
  PROD_VERSION: 3-2-15
  dockerTag: '$CI_BUILD_REF'
  DOCKER_REPO: registry:5000
  IMAGE_BASE_NAME: slogan
  STSERVER: 192.168.9.151
  RUNHOME: /home/gitlab-runner
 
#  IMAGE: $DOCKER_REPO/$IMAGE_BASE_NAME:$CI_BUILD_REF

stages:
  - build
  - test
  - r12n
#  - dp2stage

BuildImg:
  stage: build
  tags:
#    - sloganim
    - slogan6
  script:
    - docker build -t $IMAGE_BASE_NAME .
    - docker images
#    - echo OkOk

Test:
  stage: test
  tags:
    - slogan6
  script:
    - docker run --rm -e nicname="joe" $IMAGE_BASE_NAME | grep "Hi"

    

RecordImg:
  variables:
    RELEASE_IMAGE: $DOCKER_REPO/$IMAGE_BASE_NAME:latest
  stage: r12n
  tags:
    - slogan6
  script:
#    - docker tag $IMAGE_BASE_NAME $IMAGE
#    - echo $IMAGE
    - docker tag $IMAGE_BASE_NAME $DOCKER_REPO/$IMAGE_BASE_NAME:$(echo $CI_BUILD_REF | cut -c 1-7)
    - echo $DOCKER_REPO/$IMAGE_BASE_NAME:$(echo $CI_BUILD_REF | cut -c 1-7 )
    - docker push $DOCKER_REPO/$IMAGE_BASE_NAME:$(echo $CI_BUILD_REF | cut -c 1-7 )
#    - docker push $IMAGE      
    - docker tag $IMAGE_BASE_NAME $RELEASE_IMAGE 
    - docker push $RELEASE_IMAGE      
#
    - echo $PROD_VERSION    
    - echo $DOCKER_REPO/$IMAGE_BASE_NAME:$PROG_VERSION_$(echo $CI_BUILD_REF | cut -c 1-7 )

#
#
#Deploy2stage:
#  variables:
#    RELEASE_IMAGE: $DOCKER_REPO/$IMAGE_BASE_NAME:latest
#  stage: dp2stage
#  tags:
#    - sloganindo
#  script:
#    - echo 123
#    - echo $RELEASE_IMAGE
##    - ssh deploy@192.168.9.151 "sudo -u deploy docker pull $RELEASE_IMAGE"
#    - ansible-playbook -i $RUNHOME/ahosts $RUNHOME/get_latest.yml --extra-vars "$RELEASE_IMAGE"
#
       